version = 1

# ======================================================
# 🟣 JavaScript / TypeScript (Angular Frontend)
# ======================================================
[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  import_path = "geocalc-frontend"



# ======================================================
# 🟠 Java (Spring Boot Backend)
# ======================================================
[[analyzers]]
name = "java"
enabled = true
  [analyzers.meta]
  import_path = "geocalc-backend/peter.ngo.geocalc3d"
