name: Build & Test API (no deploy)

on:
  push:
    branches: [ main, master ]
    paths: [ 'geocalc-backend', '.github/workflows/build-api.yml' ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: geocalc-backend } }
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive, fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17', cache: 'maven' }
      - run: mvn -B -ntp -f peter.ngo.geocalc3d/pom.xml clean verify
      - run: mvn -B -ntp -f peter.ngo.geocalc3d/pom.xml -DskipTests package
      - uses: actions/upload-artifact@v4
        with:
          name: backend-tests
          path: geocalc-backend/**/target/surefire-reports/**
          if-no-files-found: 'ignore'
