name: CI Pipeline

on:
  push:
    branches: [ main, master ]
    paths:
      - '.github/workflows/**'
      - 'geocalc-frontend/**'
      - 'geocalc-backend/**'
      - '.gitmodules'
  pull_request:
    branches: [ main, master ]
    paths:
      - '.github/workflows/**'
      - 'geocalc-frontend/**'
      - 'geocalc-backend/**'
      - '.gitmodules'

jobs:
  frontend:
    name: Angular Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: geocalc-frontend
    steps:
      - name: Checkout (inkl. Submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Node einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'geocalc-frontend/package-lock.json'

      # Nur nötig, wenn du Karma/ChromeHeadless nutzt
      - name: Chrome bereitstellen
        uses: browser-actions/setup-chrome@v1

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Tests (ChromeHeadless)
        env:
          CHROME_BIN: ${{ env.CHROME_PATH }}
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Build (Prod)
        run: npm run build -- --configuration=production

      - name: Coverage/Artefakte hochladen
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage
          path: geocalc-frontend/coverage/**

  backend:
    name: Spring Boot Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: geocalc-backend/peter.ngo.geocalc3d
    steps:
      - name: Checkout (inkl. Submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Temurin JDK einrichten
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Tests + Verify
        run: ./mvnw -B -ntp clean verify

      - name: Jar bauen (skip tests)
        run: ./mvnw -B -ntp -DskipTests package

      - name: Reports/Artefakte hochladen
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spring-reports
          path: |
            geocalc-backend/peter.ngo.geocalc3d/target/site/**
            geocalc-backend/peter.ngo.geocalc3d/target/*.jar
